### PR TITLE
mobyte

### PR DESCRIPTION
**Pull request by mobyte0**

### CODE REVIEW

**Comment by scott-linder** [comment]
Agreed that we can factor out the repeated bits in reddit, but we can get to that later. Also, as you've already brought up moby

**Comment by scott-linder** [comment]
Larger issue is failure to trap some exceptions which are causing the bot to crash in normal operation.

For example I tried a bare `!reddit` and the bot died with:
```
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

**Comment by JPyPi** [comment]
Mobyte, you might put some of these features in different branches so that they can each be pulled in and merged with master individually. Some of these features could be merged, while others might need a little work. (e.g. tweet doesn't look like it actually tweets.)

**Comment by scott-linder** [comment]
Love it :+1: 

Merged manually, closing this PR :heart:

**Pull request closed without merging**
